include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/.dart_tool/**'
    - '**/build/**'
    - '**/android/**'
    - '**/ios/**'
    - '**/web/**'
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
